### ISSUE TITLE
Finalize all the attribute code from Salcols Mod and UA

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/UltimateApocalypse_THB#25]
# TODO List:
With the help of Salcol's Mod we'll fix some urgent issues with the current version in order to arrange a new public release.

- [ ]  Introduce Salcols latest changes to the **v1.9** branch and fix possible merge conflicts and crashes.

## Check all the races attribute code: @everybody

- [ ] Evaluate Chaos Space Marines changes
- [ ] Evaluate Space Marines changes
- [ ] Evaluate Imperial Guard changes
- [ ] Evaluate Necron changes
- [ ] Evaluate Orks changes
- [ ] Evaluate IDH changes
- [ ] Evaluate Dark Eldar changes
- [ ] Evaluate Chaos Daemons changes
- [ ] Evaluate Tyranids changes
- [ ] Evaluate Sisters of Battle changes
- [ ] Evaluate Tau changes
- [ ] Evaluate Eldar changes

## Introduce some of the GRGE features (We were holding  them back for way too long): @Fragjacker

- [ ] Add Necron Triolith
- [ ] Add Ork Mega Gargant
- [ ] Replace Legio Titanicus Imperator Titan with GRGE version
- [ ] Replace Legio Titanicus Warlord Titan with GRGE version
- [ ] Add subspace spire as new HQ and use monoliths as new spammable "baracks" to help the AI
- [ ] Remove Legio Titanicus addon and replace completely with GRGE units.
- [ ] Make the

## Rework the AI once the above has been finished: @Thudmeizer 

- [ ] Rework Chaos Space Marines AI
- [ ] Rework Space Marines AI
- [ ] Rework Imperial Guard AI
- [ ] Rework Necron AI
- [ ] Rework Orks AI
- [ ] Rework IDH AI
- [ ] Rework Dark Eldar AI
- [ ] Rework Chaos Daemons AI
- [ ] Rework Tyranids AI
- [ ] Rework Sisters of Battle AI
- [ ] Rework Tau AI
- [ ] Rework Eldar AI
